#!/usr/bin/env python3
"""Render index.html the way GitHub Pages will, without needing Ruby.

GitHub Pages builds this site with Jekyll. This script does the same job for
the one page that uses Liquid, so you can eyeball a content change before
pushing it. It is a preview aid, not the build — GitHub is still the
authority on what ships.

Usage, from the repo root:

    uv run --with python-liquid --with markdown --with pyyaml tools/preview.py

Then open the preview.html it writes. That file is gitignored.
"""
import os
import re

import markdown
import yaml
from liquid import Environment

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

env = Environment()
env.add_filter("markdownify", lambda s: markdown.markdown(str(s)))

site = dict(yaml.safe_load(open("_config.yml", encoding="utf-8")))
site["data"] = {
    fn[:-4]: yaml.safe_load(open(os.path.join("_data", fn), encoding="utf-8"))
    for fn in os.listdir("_data")
    if fn.endswith(".yml")
}

src = open("index.html", encoding="utf-8").read()
m = re.match(r"^---\n.*?\n---\n", src, re.S)
if not m:
    raise SystemExit("index.html has no Jekyll front matter — nothing to render.")

out = env.from_string(src[m.end():]).render(site=site)
out = out.replace(
    "<head>",
    "<head>\n    <!-- LOCAL PREVIEW — generated by tools/preview.py, not committed. -->",
    1,
)
with open("preview.html", "w", encoding="utf-8") as f:
    f.write(out)

print(f"Wrote preview.html ({len(out.splitlines())} lines). Open it in a browser.")
